title: Out of the Frying Pan and Into the Fire
author: HobnobMancer
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Working through the GitHub Lab training pathways as part of my PhD
  This is a mini-blog covering different aspects of the PhD
  and how I overcame/overcome different hurdels

# social links
twitter_username: your-twitter-handle
github_username:  HobnobMancer
linkedin_URL: https://www.linkedin.com/in/emma-eliza-hobbs/?trk=people-guest_profile-result-card_result-card_full-click&originalSubdomain=uk

show_excerpts: true # set to false to remove excerpts on the homepage


# appearance
theme: minima
